name: DreamDisplays
version: '${version}'
authors: [arsmotorin, INotSleep]
description: 'Plugin for Dream Displays mod.'
main: com.inotsleep.dreamdisplays.DreamDisplaysPlugin
api-version: '1.21'
folia-supported: true
