modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "GNU GPL"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
clientSideOnly=true

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Dream Displays"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile="forgetest.png"
authors = "${mod_authors}"
description = '''Mod to watch youtube videos in Minecraft with friends'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
