# Crowdin configuration file for Dream Displays mod
project_id: "dream-displays"
api_token_env: "CROWDIN_API_TOKEN"
base_path: "."
preserve_hierarchy: true

files:
  - source: "/fabric/src/main/resources/lang/en.json"
    translation: "/fabric/src/main/resources/lang/%two_letters_code%.json"
    update_option: "update_as_unapproved"
    dest: "/fabric/src/main/resources/lang/%two_letters_code%.json"

# Language mapping for special cases
languages_mapping:
  two_letters_code:
    uk: "uk"    # Ukrainian
    de: "de"    # German
    pl: "pl"    # Polish
    ru: "ru"    # Russian

# Translation settings
translation_providers:
  1:
    name: "crowdin"

# Export settings
export_settings:
  export_only_approved: false
  skip_untranslated_strings: false
  export_string_that_passed_workflow: false
