# Project
version=1.10.0-dev
group=com.dreamdisplays

# Gradle
org.gradle.jvmargs=-Xmx2G -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Kotlin
kotlin.incremental=true
kotlin.incremental.java=true
kotlin.caching.enabled=true

org.gradle.java.installations.auto-download=false

org.gradle.java.installations.paths=C:\\Users\\Hennri Cortez\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-25.0.1.8-hotspot
